import os
import shutil
import time
from pathlib import Path
from typing import Dict, Any, Optional
from app.core.config import settings


def get_dir_size_bytes(path: Path) -> int:
    """Calculates total byte size of a directory recursively."""
    if not path.exists():
        return 0
    total = 0
    try:
        for entry in os.scandir(path):
            if entry.is_file(follow_symlinks=False):
                total += entry.stat().st_size
            elif entry.is_dir(follow_symlinks=False):
                total += get_dir_size_bytes(Path(entry.path))
    except (PermissionError, FileNotFoundError):
        pass
    return total


def cleanup_task_intermediates(task_id: str) -> int:
    """
    Deletes temporary partial movie chunks generated by Manim for a specific task.
    This frees up 70-80% of disk space while keeping the final MP4 intact.
    Returns bytes freed.
    """
    if not settings.CLEANUP_INTERMEDIATES:
        return 0

    scene_dir = settings.VIDEOS_DIR / f"scene_{task_id}"
    if not scene_dir.exists():
        return 0

    freed_bytes = 0
    try:
        # Manim stores partial animation segments in partial_movie_files directories
        for partial_dir in scene_dir.glob("**/partial_movie_files"):
            if partial_dir.is_dir():
                size = get_dir_size_bytes(partial_dir)
                shutil.rmtree(partial_dir, ignore_errors=True)
                freed_bytes += size

        # Clean stray log or temp files in task folder
        for stray in scene_dir.glob("*.log"):
            try:
                freed_bytes += stray.stat().st_size
                stray.unlink(missing_ok=True)
            except Exception:
                pass
    except Exception as e:
        print(f"Warning: Failed to clean intermediates for task {task_id}: {e}")

    return freed_bytes


def prune_old_media(
    max_videos: Optional[int] = None,
    max_storage_mb: Optional[int] = None
) -> Dict[str, Any]:
    """
    Applies an LRU pruning policy to media/videos, keeping disk usage bounded.
    Deletes the oldest rendered tasks when count or storage exceeds limits.
    Also cleans up corresponding scene scripts in generated_scenes/.
    """
    max_count = max_videos if max_videos is not None else settings.MAX_STORED_VIDEOS
    max_mb = max_storage_mb if max_storage_mb is not None else settings.MAX_STORAGE_MB
    max_bytes = max_mb * 1024 * 1024

    if not settings.VIDEOS_DIR.exists():
        return {"deleted_count": 0, "freed_mb": 0.0, "total_remaining_mb": 0.0}

    # Discover all scene directories
    scene_dirs = [d for d in settings.VIDEOS_DIR.iterdir() if d.is_dir() and d.name.startswith("scene_")]
    if not scene_dirs:
        return {"deleted_count": 0, "freed_mb": 0.0, "total_remaining_mb": 0.0}

    # Sort by modification time (oldest first)
    scene_info = []
    total_size = 0
    for sd in scene_dirs:
        try:
            mtime = sd.stat().st_mtime
            size = get_dir_size_bytes(sd)
            total_size += size
            scene_info.append({"path": sd, "mtime": mtime, "size": size, "name": sd.name})
        except (FileNotFoundError, PermissionError):
            continue

    scene_info.sort(key=lambda x: x["mtime"])

    deleted_count = 0
    freed_bytes = 0

    # Prune while exceeding count or size limits
    while scene_info and (len(scene_info) > max_count or total_size > max_bytes):
        oldest = scene_info.pop(0)
        target_path = oldest["path"]
        task_id = oldest["name"].replace("scene_", "")

        try:
            shutil.rmtree(target_path, ignore_errors=True)
            freed_bytes += oldest["size"]
            total_size -= oldest["size"]
            deleted_count += 1

            # Remove corresponding scene python file
            py_file = settings.SCENES_DIR / f"scene_{task_id}.py"
            if py_file.exists():
                py_file.unlink(missing_ok=True)
        except Exception as e:
            print(f"Warning: Failed to prune {target_path}: {e}")

    # Clean legacy TeX and text cache files older than 48 hours
    cleanup_tex_cache(hours_threshold=48)

    return {
        "deleted_count": deleted_count,
        "freed_mb": round(freed_bytes / (1024 * 1024), 2),
        "total_remaining_mb": round(total_size / (1024 * 1024), 2),
        "remaining_scenes": len(scene_info)
    }


def cleanup_tex_cache(hours_threshold: int = 48) -> int:
    """Prunes stale LaTeX and SVG text build files older than the threshold."""
    now = time.time()
    cutoff = now - (hours_threshold * 3600)
    freed = 0

    for sub_dir in ["Tex", "texts"]:
        dir_path = settings.MEDIA_DIR / sub_dir
        if not dir_path.exists():
            continue
        try:
            for item in dir_path.glob("**/*"):
                if item.is_file():
                    try:
                        if item.stat().st_mtime < cutoff:
                            freed += item.stat().st_size
                            item.unlink(missing_ok=True)
                    except Exception:
                        pass
        except Exception:
            pass

    return freed
